#!/bin/sh

cat <<EOF
This is a bugs.python.org S2I builder image:
To use it, install S2I: https://github.com/openshift/source-to-image
Sample invocation:
s2i build https://github.com/python/bpo-builder python/bpo-builder bugs-python-org
You can then run the resulting image via:
docker run -p 8080:8080 bugs-python-org
EOF
